all:
  vars:
    ansible_ssh_common_args: -o StrictHostKeyChecking=no
#    istio_version: 1.4.6
  children:
    master:
      hosts:
        k8s-master:
          ansible_user: vagrant
          node_ip: 192.168.50.10
          ansible_ssh_private_key_file: ../.vagrant/machines/k8s-master/virtualbox/private_key
          ansible_port: 2222
          ansible_ssh_host: 127.0.0.1
    worker:
      hosts:
        node-1:
          ansible_user: vagrant
          node_ip: 192.168.50.11
          ansible_ssh_private_key_file: ../.vagrant/machines/node-1/virtualbox/private_key
          ansible_port: 2200
          ansible_ssh_host: 127.0.0.1
        node-2:
          ansible_user: vagrant
          node_ip: 192.168.50.12
          ansible_ssh_private_key_file: ../.vagrant/machines/node-2/virtualbox/private_key
          ansible_port: 2201
          ansible_ssh_host: 127.0.0.1
        node-3:
          ansible_user: vagrant
          node_ip: 192.168.50.13
          ansible_ssh_private_key_file: ../.vagrant/machines/node-3/virtualbox/private_key
          ansible_port: 2202
          ansible_ssh_host: 127.0.0.1
