---
git_meetup_frontend_site_url: git@github.com:belenot/meeting-site.git
git_meetup_backend_site_url: git@github.com:belenot/meetup-backend.git
install_mode: prod
meetup_site:
  database:
    url: jdbc:postgresql://localhost:5432/meetup
    username: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      33393032633431306666363063633838373462306465306433333561363630396235653532323465
      6165353763613361333536313762646234623764666266640a653632636437656562333834323461
      31643866626465323735356431336238356538306635626564643537373362653365373065303762
      3535333961656539660a306336326430666161303236313163353166393231393037303635323765
      3139
    password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      35633431313730336261623637633831393435333164383231306365306432383330393338356238
      3362313363306332646335616230663934356538366165310a333465323062633064653238323766
      62346139383862393639376363306439353965306165643939313036323734376238313332343630
      3366336164306433330a396631393639656161646465663436306539313933626430336161363739
      6234
    changelog_file: database.sql
template_nginx_conf: false # Set true when do automatic letsencrypt setup.
                           # Until that, nginx template will brake manual letsencrypt setup
clean_gradle: false
