---
git_meetup_frontend_site_url: git@github.com:belenot/meeting-site.git
git_meetup_backend_site_url: git@github.com:belenot/meetup-backend.git
install_mode: prod
meetup_site:
  database:
    url: jdbc:postgresql://localhost:5432/meetup
    username: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      35313037343464316237336633333261383634333762626262653661636435623966396438306666
      3861323062636464613636343233313566326331636265340a643630303633613666373361343764
      31326563653630653263643635366638363865306465333766666332336336333766656566363635
      3766346132653134640a303465376630383130626131346463333664306536623464633564623634
      30333039633439613933373464346363343036386363366464623934353264353732
    password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      63616131313437396537316663386233623266376130653866616263656663653561636266663466
      3935366663666266613938646430336136393664326666650a333233313938303134323038396331
      64396232646566383366646231376535356136313064653863636138393031386436656561343963
      6438333030326338300a333833303438363762623963643032656363643132633232323463386337
      6165
    changelog_file: database.sql
template_nginx_conf: true # Set true when do automatic letsencrypt setup.
                           # Until that, nginx template will brake manual letsencrypt setup
clean_gradle: false
