---
node_ip: 192.168.50.10
ca_passphrase: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  33316638623666346231336265343266356330663466363563383335666332333962383235343466
  3966343665626439323361613962613666383534626433350a666137383832633763653063313664
  63653335666434616466623134343938363463323762633365643134643333366333303762353133
  3466643333646337300a326532396262646334306464333332353338623439323937313034633336
  33356366323839343036653038626632396163326439313738373364633862393237