---
- name: docker status
  service: 
    name: docker 
    state: started
  become: yes

- name: generate join command
  shell: kubeadm token create --print-join-command > ./join-command

- name: fetch join command
  fetch: 
    src: join-command 
    dest: join-command

- name: fetch admin kubeconfig
  fetch: 
    src: .kube/config 
    dest: kubeconfig